# Generated by Django 6.0.4 on 2026-04-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('camera', 'Cameras'), ('cable', 'Cables'), ('storage', 'Storage (NVR/DVR)'), ('capacity', 'HDD Capacity'), ('switch', 'PoE Switches')], max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'cctv',
            },
        ),
        migrations.DeleteModel(
            name='CCTVComponent',
        ),
    ]
