# Generated by Django 6.0.4 on 2026-04-15 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv_app', '0003_category_alter_product_table_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('camera', 'Camera'), ('cable', 'Cable'), ('recorder', 'Recorder'), ('channel', 'Channel'), ('poe', 'PoE Switch')], max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.CreateModel(
            name='CCTVQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable_quotes', to='cctv_app.priceitem')),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_quotes', to='cctv_app.priceitem')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_quotes', to='cctv_app.priceitem')),
                ('poe_switch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poe_quotes', to='cctv_app.priceitem')),
                ('recorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorder_quotes', to='cctv_app.priceitem')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
