# Generated by Django 6.0.4 on 2026-04-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv_app', '0004_priceitem_remove_product_category_cctvquotation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('camera', 'Camera'), ('cable', 'Cable'), ('recorder', 'Recorder'), ('channel', 'Channel'), ('poe', 'PoE Switch')], max_length=50)),
                ('item_type', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='CCTVQuotation',
        ),
        migrations.DeleteModel(
            name='PriceItem',
        ),
    ]
